---
- name: Install Joomla and VirtualHost (httpd.conf에 추가)
  hosts: rocky
  become: yes
  vars:
    document_root: "/var/www/jola"
    joomla_url: "https://downloads.joomla.org/cms/joomla5/5-3-0/Joomla_5-3-0-Stable-Full_Package.zip?format=zip"
    joomla_archive: "/home/jola/joomla.zip"
  tasks:
    - name: Useradd joomla
      ansible.builtin.user:
        name: joomla
        state: present
        create_home: yes 

    - name: Create Public_html Directory
      ansible.builtin.file:
        path: /home/jola/public_html
        state: directory
        mode: '0755'

    - name: Create Joomla DocumentRoot
      ansible.builtin.file:
        path: "{{ document_root }}"
        state: directory
        owner: apache
        group: apache
        mode: '0755'

    - name: Joomla 다운로드
      get_url:
        url: "{{ joomla_url }}"
        dest: "{{ joomla_archive }}"
        mode: '0644'

    - name: Joomla 압축 해제
      unarchive:
        src: "{{ joomla_archive }}"
        dest: "{{ document_root }}"
        remote_src: yes
        owner: apache
        group: apache

    - name: Joomla directory permission
      ansible.builtin.command:
        cmd: chmod -R 755 /home/jola

    - name: Add VirtualHost to httpd.conf
      blockinfile:
        path: /etc/httpd/conf/httpd.conf
        block: |
          <VirtualHost *:80>
              ServerName www.dkdk.com
              DocumentRoot {{ document_root }}
              <Directory {{ document_root }}>
                  AllowOverride All
                  Require all granted
              </Directory>
              ErrorLog /var/log/httpd/dragon6_error.log
              CustomLog /var/log/httpd/dragon6_access.log combined
          </VirtualHost>
        marker: "# {mark} ANSIBLE JOOMLA VHOST www.dkdk.com"
        insertafter: EOF

    - name: httpd reload
      service:
        name: httpd
        state: reloaded

# - name: Make Database Joomla
#  hosts: ubuntu
#  become: yes
#  collections:
#    - community.mysql
#  vars:
#    db_name: joomla
#    db_user: joomla
#    db_password: "asd123!@"
#    ansible_python_interpreter: /usr/bin/python3
#  tasks:
#    - name: Install PyMySQL on target host
#      ansible.builtin.apt:
#        name: python3-pymysql
#        state: present

#    - name: Create MySQL DB
#      mysql_db:
#        login_unix_socket: /var/run/mysqld/mysqld.sock
#        name: "{{ db_name }}"
#        state: present
#        login_user: root
#        login_password: "asd123!@"

#    - name: Create MySQL User and Grant Permissions
#      mysql_user:
#        login_unix_socket: /var/run/mysqld/mysqld.sock
#        name: "{{ db_user }}"
#        password: "{{ db_password }}"
#        priv: "{{ db_name }}.*:ALL"
#        state: present
#        host: "%"
#        login_user: root
#        login_password: "asd123!@"
