---
- name: Rocky9.5 DNS setup
  hosts: all
  gather_facts: yes
  tasks:
    #- name: Check if Named is installed
    #  ansible.builtin.shell: command -v named
    #  register: bind
    #  changed_when: false
    #  failed_when: false

    - name: Install dns-server
      ansible.builtin.dnf:
        name:
          - bind
        state: present
      #when: bind.rc != 0

    # named.conf 옵션 변경
    - name: port any
      ansible.builtin.replace:
        path: /etc/named.conf
        regexp: 'listen-on port 53 { 127.0.0.1; };'
        replace: 'listen-on port 53 { any; };'

    - name: allow-query
      ansible.builtin.replace:
        path: /etc/named.conf
        regexp: 'allow-query     { localhost; };'
        replace: 'allow-query     { any; };'
      

    # DNS zone 파일 설정
    - name: Create zone file
      ansible.builtin.copy:
        dest: "/var/named/smt.it.zone"
        content: |
          $TTL 1D
          @       IN SOA  ns.smt.it. smt.smt.it (
                                                  250226  ; serial
                                                  1D      ; refresh
                                                  1H      ; retry
                                                  1W      ; expire
                                                  3H )    ; minimum
                  NS      ns.smt.it.
                  A       10.184.0.53

          ns      IN      A       10.184.0.53
          www     IN      A       10.184.0.100
          ftp     IN      A       10.248.0.102

    # DNS zone 파일 설정
    - name: Create zone file
      ansible.builtin.copy:
        dest: "/var/named/smt.local"
        content: |
          $TTL 1D
          @       IN SOA  ns.smt.it. smt.smt.it (
                                                  250226  ; serial
                                                  1D      ; refresh
                                                  1H      ; retry
                                                  1W      ; expire
                                                  3H )    ; minimum
                  NS      ns.smt.it.
                  A       10.184.0.53

          ns      IN      A       10.184.0.53
          smb     IN      A       10.248.0.101
          mo      IN      A       10.248.0.105
          mrtg    IN      A       10.248.0.105
          DB      IN      A       10.248.0.100
          R1      IN      A       172.16.0.130
          R2      IN      A       10.0.0.2
          R3      IN      A       10.8.0.2
          R4      IN      A       10.16.0.2
          R5      IN      A       10.80.0.2
          R6      IN      A       10.84.0.2
          R7      IN      A       10.64.0.2
          R8      IN      A       10.68.0.2
          R9      IN      A       10.72.0.2
          R10     IN      A       10.96.0.2
          R11     IN      A       10.100.0.2
          R12     IN      A       10.108.0.2
          R13     IN      A       10.192.0.2
          R14     IN      A       10.136.0.2
          R15     IN      A       10.152.0.2
          R16     IN      A       10.144.0.2

    # DNS rfc 파일 설정
    - name: DNS rfc1912.zone setting
      ansible.builtin.blockinfile:
        path: "/etc/named.rfc1912.zones"
        block: |
          zone "smt.it" IN{
                  type master;
                  file "smt.it.zone";
                  allow-update { none; };
                  allow-transfer { 12.192.0.20; };
          };
          zone "smt2.it" IN {
                  type slave;
                  masters { 12.192.0.20; };
                  file "slaves/zone.smt2.it.db";
          };
          zone "smt.local" IN {
                  type master;
                  file "smt.local";
                  allow-update { none; };
                  allow-transfer { none; };
                  allow-query { 10.0.0.0/8; };
          };
      when: ansible_os_family == "RedHat"

    # DNS 서비스 재시작
    - name: Restart Named Service
      ansible.builtin.systemd:
        name: named
        state: restarted
        enabled: true
      when: ansible_os_family == "RedHat"