---
- name: Rocky9.5 nfs setup (Server)
  hosts: all
  tasks:
    - name: Install NFS (Rocky9.5)
      ansible.builtin.dnf:
        name:
          - nfs-utils
        state: present

    # NFS 서버에서 공유하기 위한 디렉토리 생성
    - name: Make Directory (nfs)
      ansible.builtin.file:
        path: "/nfs"
        state: directory
        mode: '0755'

    # exports 파일에서 nfs 디렉토리에 대한 내용 추가
    - name: Configure /etc/exports
      ansible.builtin.copy:
        dest: /etc/exports
        content: |
          /nfs *(rw,sync,no_root_squash)
        owner: root
        group: root
        mode: '0644'

    # NFS 서비스 시작 및 재시작
    - name: Exports NFS shares
      ansible.builtin.systemd:
        name: nfs-server
        enabled: true
        state: started

    - name: NFS service restart
      ansible.builtin.systemd:
        name: nfs-server
        state: restarted