---
- name: Install ownCloud on Ubuntu
  hosts: ubuntu
  become: yes
  vars:
    owncloud_root: "/var/www/owncloud"
  tasks:
    - name: Install Apache, PHP, MariaDB, and dependencies
      apt:
        name:
          - libapache2-mod-php
          - php
          - php-mysql
          - php-xml
          - php-zip
          - php-curl
          - php-gd
          - php-mbstring
          - php-intl
          - wget
          - unzip
        state: present
        update_cache: yes

    - name: Download ownCloud
      get_url:
        url: https://download.owncloud.org/community/owncloud-latest.zip
        dest: /tmp/owncloud.zip

    - name: Unarchive ownCloud
      unarchive:
        src: /tmp/owncloud.zip
        dest: /var/www/
        remote_src: yes
        owner: www-data
        group: www-data

    - name: Set permissions
      file:
        path: "{{ owncloud_root }}"
        owner: www-data
        group: www-data
        recurse: yes

    - name: Add VirtualHost for ownCloud
      copy:
        dest: /etc/apache2/sites-available/owncloud.conf
        content: |
          <VirtualHost *:80>
              ServerName owncloud.local
              DocumentRoot {{ owncloud_root }}
              <Directory {{ owncloud_root }}>
                  AllowOverride All
                  Require all granted
              </Directory>
              ErrorLog ${APACHE_LOG_DIR}/owncloud_error.log
              CustomLog ${APACHE_LOG_DIR}/owncloud_access.log combined
          </VirtualHost>

    - name: Enable ownCloud site
      command: a2ensite owncloud.conf
      args:
        creates: /etc/apache2/sites-enabled/owncloud.conf

    - name: Reload apache2
      service:
        name: apache2
        state: reloaded

