---
- name: Webhard Source Build (pydio)
  hosts: ubun
  tasks:
    - name: Install packages
      ansible.builtin.apt:
        name:
          - gcc
          - make
          - git
          - golang-go

    # WebHard로 사용할 디렉토리 생성
    - name: Make Directory
      ansible.builtin.file:
        path: "/var/www/pydio"
        state: directory
        mode: '0755'

    # Github에서 cells파일 clone
    - name: Git Clone cells.git
      ansible.builtin.git:
        repo: https://github.com/pydio/cells.git
        dest: '/var/www/pydio'
        version: main
        force: yes

    # Source build를 하기 위해 make 명령 수행
    - name: Source Build cells.git
      ansible.builtin.command:
        cmd: make dev
      args:
        chdir: /var/www/pydio

- name: Make Database (pydio)
  hosts: ubuntu
  become: yes
  gather_facts: yes
  collections:
    - community.mysql
  vars:
    db_name: pydio
    db_user: root
    db_password: "asd123!@"
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Install PyMySQL on target host
      ansible.builtin.apt:
        name:
          - python3-pymysql
          - mariadb-server
        state: present
        update_cache: yes

    # cells에 사용하기 위한 DB 생성
    - name: Create MySQL DB
      mysql_db:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: "{{ db_name }}"
        state: present
        login_user: root
        login_password: "asd123!@"

    # cells의 사용자 권한 부여
    - name: Create MySQL User and Grant Permissions
      mysql_user:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: "{{ db_name }}.*:ALL"
        state: present
        host: "%"
        login_user: root
        login_password: "asd123!@"

    # MariaDB 서비스 재시작
    - name: MariaDB Service Restart
      ansible.builtin.systemd:
        name: mariadb
        state: restarteda

    - name: Apache2 Service Restart
      ansible.builtin.systemd:
        name: apache2
        state: restarted

#- name: Cells Configure (pydio)
#  hosts: ubuntu
#  tasks:
#    - name: Cells Setting (pydio)
#      ansible.builtin.expect:
#        command: ./cells configure --cli
#        responses:
#          "Database Connection Type:": "\r"
#          "Database Hostname:": "\r"
#          "Database Port:": "\r"
#          "Database Name:": "\r"
#          "Database User:": "\r"
#          "Database Password.*:": "\r"
#          "Do you wish to configure a MongoDB connection.*": "n\r"
#          "Admin Login:": "\r"
#          "Admin Password:": "asd123!@\r"
#          "Confirm Password:": "asd123!@\r"
#      args:
#        chdir: /home/pydio
